// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmozlegzaawqnclvrhxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtb3psZWd6YWF3cW5jbHZyaHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Nzc3MTYsImV4cCI6MjA2NDI1MzcxNn0.TLxVSLkIYBZElXuHdRwbjLYDpBVXlHv_1gGoWEXIdfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);